src/LITReview/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('blog/', include("flux.urls")),
    path('followers/', include("followers.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/accounts/urls.py
from django.urls import path, include

from .views import Signup, Profile, CustomLoginView, CustomLogoutView

app_name = "accounts"

urlpatterns = [

    path('signup/', Signup.as_view(), name="signup"),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    #path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    #path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    #path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    #path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    #path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    #path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/<int:pk>/', Profile.as_view(), name="profile"),
]

src/flux/urls.py
from django.urls import path, re_path

from .views import Flux, CreateTicket, CreateReview, ViewTicket, ViewReview, UpdateTicket, UpdateReview, DeleteTicket, DeleteReview, MyPost

app_name = "blog"

urlpatterns = [
    path('', Flux.as_view(), name="flux"),
    path('mypost/', MyPost.as_view(), name="my-post"),
    path('ticket/create/', CreateTicket.as_view(), name="create-ticket"),
    re_path(r'^review/create/(?P<pk>\d+)/$', CreateReview.as_view(), name="create-review"),
    path('ticket/<int:pk>/', ViewTicket.as_view(), name="view-ticket"),
    path('review/<int:pk>/', ViewReview.as_view(), name="view-review"),
    path('ticket/delete/<int:pk>/', DeleteTicket.as_view(), name="delete-ticket"),
    path('review/delete/<int:pk>/', DeleteReview.as_view(), name="delete-review"),
    path('ticket/update/<int:pk>/', UpdateTicket.as_view(), name="update-ticket"),
    path('review/update/<int:pk>/', UpdateReview.as_view(), name="update-review"),
    #path('create/review/<int:pk>/', CreateReview.as_view(), name="create-review"),
]

src/followers/urls.py
from django.urls import path

from .views import GetCustomUser, FollowedFollowers, follow_user, unfollow_user

app_name = "followers"

urlpatterns = [
    path('search_users/', GetCustomUser.as_view(), name="get-users"),
    path('social/', FollowedFollowers.as_view(), name="social"),
    path('follow/<int:pk>/', follow_user, name="follow"),
    path('unfollow/<int:pk>', unfollow_user, name="unfollow"),
]

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}{{ page_title|default:"LITReview" }}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static '/icon/favicon-16x16.png' %}">

</head>
<body class="w-100">

<header class="p-3 text-white">
    {% block navbar %}
        {% include 'navbar.html' %}
    {% endblock %}
</header>

<main>

    <article>
        {% block content %}
        {% endblock %}
    </article>


</main>

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

</body>

</html>

src/templates/footer.html
{% block footer %}
    <footer class="text-white text-center align-items-center">
        <div class="row">
            <div class="col-12 align-items-center">
                <p>@LITReview - 2022</p>
            </div>
        </div>
    </footer>
{% endblock %}

src/templates/navbar.html
{% load static %}

<nav id="navbar" class="nav">

    <div class="container">
        <div class="row align-items-center">
            <div class="col-2">
                <a href="{% url 'blog:flux' %}" class="" id="logo">
                    <img class="logo" src="{% static '/logo/logo_pp.png' %}"/>
                </a>
            </div>
            <div class="col-6">
                <ul class="nav justify-content-center  display-6">
                    <li class="nav-item mx-3">
                        <a href="{% url 'blog:flux' %}" class="nav-link active px-2 text-white">Flux</a>
                    </li>
                    <li class="nav-item mx-3">
                        <a href="{% url 'blog:my-post' %}" class="nav-link px-2 text-white">Posts</a>
                    </li>
                    <li class="nav-item mx-3">
                        <a href="{% url 'followers:get-users' %}" class="nav-link px-2 text-white">Abonnements</a>
                    </li>
                </ul>
            </div>
            <div class="col-4 text-end">
                {% if user.is_authenticated %}
                    <div id="user-link" class="col-6">
                        Bonjour,
                        <a href="{% url 'accounts:profile' pk=user.id %}"><strong>{{ request.user }}</strong></a>
                    </div>
                    <div class="row text-end">
                        <div class="col-6 mt-3">
                            <a href="{% url 'accounts:logout' %}" type="button" class="btn btn-warning">Se déconnecter</a>
                {% else %}
                            <a href="{% url 'accounts:login' %}" type="button" class="btn btn-outline-light me-2">Se connecter</a>
                            <a href="{% url 'accounts:signup' %}" type="button" class="btn btn-warning">S'inscrire</a>
                {% endif %}
                        </div>
                    </div>

            </div>

        </div>
    </div>
</nav>