src/LITReview/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('blog/', include("flux.urls")),
    path('followers/', include("followers.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/flux/urls.py
from django.urls import path, re_path

from .views import Flux, CreateTicket, CreateReview, ViewTicket, ViewReview, UpdateTicket, UpdateReview, DeleteTicket, DeleteReview, MyPost

app_name = "blog"

urlpatterns = [
    path('', Flux.as_view(), name="flux"),
    path('mypost/', MyPost.as_view(), name="my-post"),
    path('ticket/create/', CreateTicket.as_view(), name="create-ticket"),
    re_path(r'^review/create/(?P<pk>\d+)/$', CreateReview.as_view(), name="create-review"),
    path('ticket/<int:pk>/', ViewTicket.as_view(), name="view-ticket"),
    path('review/<int:pk>/', ViewReview.as_view(), name="view-review"),
    path('ticket/delete/<int:pk>/', DeleteTicket.as_view(), name="delete-ticket"),
    path('review/delete/<int:pk>/', DeleteReview.as_view(), name="delete-review"),
    path('ticket/update/<int:pk>/', UpdateTicket.as_view(), name="update-ticket"),
    path('review/update/<int:pk>/', UpdateReview.as_view(), name="update-review"),
    #path('create/review/<int:pk>/', CreateReview.as_view(), name="create-review"),
]

src/followers/urls.py
from django.urls import path

from .views import GetCustomUser, FollowedFollowers, follow_user, unfollow_user

app_name = "followers"

urlpatterns = [
    path('search_users/', GetCustomUser.as_view(), name="get-users"),
    path('social/', FollowedFollowers.as_view(), name="social"),
    path('follow/<int:pk>/', follow_user, name="follow"),
    path('unfollow/<int:pk>', unfollow_user, name="unfollow"),
]

src/followers/models.py
from django.db import models
from django.conf import settings


class UserFollows(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='following')
    followed_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='followed_by')

    class Meta:
        unique_together = ('user', 'followed_user')

src/followers/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView

from accounts.models import CustomUser
from .models import UserFollows
from .filters import UserFilter


class GetCustomUser(LoginRequiredMixin, ListView):
    """
    Liste tout les utilisateurs enregistrés sur le site.
    """
    model = CustomUser
    template_name = "users_search.html"
    context_object_name = "users"

    def get_context_data(self, *, object_list=None, **kwargs):
        users = CustomUser.objects.all()
        social = FollowedFollowers()
        userfilter = UserFilter(self.request.GET, queryset=users)
        users = userfilter.qs
        context = {'filter': userfilter, 'users': users, 'followed_users': get_followed_users(self.request),
                   'followers': get_followers(self.request)}
        return super().get_context_data(**context)


class FollowedFollowers(LoginRequiredMixin, ListView):
    """
    Liste tout les utilisateurs qui suivent l'utilisateur connecté.
    Liste tout les utilisateurs que l'utilisateur connecté suit.
    """

    model = UserFollows
    paginate_by = 10
    template_name = "social.html"
    context_object_name = "users"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['followed_users'] = get_followed_users(self.request)
        context['followers'] = get_followers(self.request)
        return context


@login_required
def follow_user(request, pk=None):
    """

    Args:
        request: Données session utilisateur.
        pk: Primary Key de l'utilisateur à suivre.

    Returns: Ajoute l'utilisateur dans les followers.

    """
    user_to_follow = CustomUser.objects.get(pk=pk).pk
    follow = UserFollows()

    if request.method == "GET":
        if pk is not None:
            follow.user_id = get_current_user(request)
            follow.followed_user_id = user_to_follow
            follow.save()
            return redirect("followers:get-users")
    else:
        raise ValueError("Pas d'id utilisateur")


@login_required
def unfollow_user(request, pk=None):
    """

    Args:
        request: Données session utilisateur.
        pk: id utilisateur à ne plus suivre.

    Returns: Retire un utilisateur de la liste des followers pour l'utilisateur connecté.

    """
    user_to_unfollow = CustomUser.objects.get(pk=pk)

    if pk is not None:
        if request.method == 'GET':
            UserFollows.objects.filter(user_id=get_current_user(request), followed_user_id=user_to_unfollow).delete()
            return redirect("followers:social")
    else:
        raise ValueError('Pas de données dans request')


@login_required
def get_current_user(request):
    """

    Args:
        request: Données session utilisateur.

    Returns: Primary Key de l'utilisateur en cours.

    """
    if request is not None:
        return CustomUser.objects.get(pk=request.user.pk).pk
    else:
        raise ValueError('Pas de données dans request')


def get_followed_users(request):
    return [CustomUser.objects.get(pk=users.followed_user.pk) for users in
            UserFollows.objects.filter(user_id=request.user.pk)]


def get_followers(request):
    return [CustomUser.objects.get(pk=users.followed_user_id) for users in
            UserFollows.objects.filter(followed_user_id=request.user.pk)]

src/followers/templates/base_followers.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block content %}

    {% block user_search %}
        {% block search %}
        {% endblock %}
        {% block search_result %}
        {% endblock %}
    {% endblock %}

    <section id="search-result" class="container border border-2 rounded-3 my-2">
        {% block social %}
            {% block followed %}
            {% endblock %}
            {% block followers %}
            {% endblock %}
        {% endblock %}
    </section>

{% endblock %}

src/followers/templates/social.html
{% extends 'base_followers.html' %}
{% load static %}

{% block title %}LITReview - Mon réseau{% endblock %}
{% block social %}

    {% block followed %}
        <div class="row text-center my-2">
        <h3>Les utilisateurs que vous suivez</h3>
        <hr>
        <table class="table table-hover align-middle">
            <thead>
            <tr>
                <td>Photo de profile</td>
                <td>Nom d'utilisateur</td>
                <td>Email</td>
                <td>Date d'inscription</td>
                <td>S'inscrire</td>
            </tr>
            </thead>
            <tbody>
            {% for user in followed_users %}
                <tr>
                    <th><img src="{% get_media_prefix %}{{ user.profile_picture }}" alt=""></th>
                    <th>{{ user.nick_name }}</th>
                    <th>{{ user.email }}</th>
                    <th>{{ user.date_joined }}</th>
                    <th><a href="{% url 'followers:unfollow' user.id %}">Ne plus suivre</a></th>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endblock %}

    {% block followers %}
        <h3>Les utilisateurs qui vous suivent</h3>
        <hr>
        <table class="table table-hover align-middle">
            <thead>
            <tr>
                <td>Photo de profile</td>
                <td>Nom d'utilisateur</td>
                <td>Email</td>
                <td>Date d'inscription</td>

            </tr>
            </thead>
            <tbody>
            {% for user in followers %}
                <tr>
                    <th><img src="{% get_media_prefix %}{{ user.profile_picture }}" alt=""></th>
                    <th>{{ user.nick_name }}</th>
                    <th>{{ user.email }}</th>
                    <th>{{ user.date_joined }}</th>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        </div>
    {% endblock %}

{% endblock %}

src/followers/templates/users_search.html
{% extends 'base_followers.html' %}
{% load static %}
{% block title %}LITReview - Utilisateur{% endblock %}
{% block user_search %}

    {% block search %}
        <section id="search-user" class="container border border-2 rounded-3 my-2">
            <div class="row mb-3">
                <div class="col text-center my-2">
                    <h3>Recherche</h3>
                    <hr>
                </div>
                <form method="GET">
                    <div class="row text-center align-items-center">
                        <div class="col-7 text-end">
                            {{ filter.form }}
                        </div>
                        <div class="col-2 text-start">
                            <button class="btn btn-primary" type="submit">Rechercher</button>
                        </div>
                    </div>
                </form>
            </div>
        </section>
    {% endblock %}
    {% block search_result %}
        <section id="search-result" class="container border border-2 rounded-3 my-2">
            <div class="row text-center my-2">
                <h3>Résultat de recherche:</h3>
                <hr>
            </div>
            <div class="col-12 text-centre">
                <table class="table table-hover align-middle">
                    <thead>
                    <tr>
                        <td>Photo de profile</td>
                        <td>Nom d'utilisateur</td>
                        <td>Email</td>
                        <td>Date d'inscription</td>
                        <td>S'inscrire</td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                        <tr>
                            <th><img src="{% get_media_prefix %}{{ user.profile_picture }}" alt=""></th>
                            <th>{{ user.nick_name }}</th>
                            <th>{{ user.email }}</th>
                            <th>{{ user.date_joined }}</th>
                            <th><a href="{% url 'followers:follow' user.id %}">Suivre</a></th>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </section>
    {% endblock %}
{% endblock %}