src/LITReview/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('blog/', include("flux.urls")),
    path('followers/', include("followers.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/flux/urls.py
from django.urls import path, re_path

from .views import Flux, CreateTicket, CreateReview, ViewTicket, ViewReview, UpdateTicket, UpdateReview, DeleteTicket, DeleteReview, MyPost

app_name = "blog"

urlpatterns = [
    path('', Flux.as_view(), name="flux"),
    path('mypost/', MyPost.as_view(), name="my-post"),
    path('ticket/create/', CreateTicket.as_view(), name="create-ticket"),
    re_path(r'^review/create/(?P<pk>\d+)/$', CreateReview.as_view(), name="create-review"),
    path('ticket/<int:pk>/', ViewTicket.as_view(), name="view-ticket"),
    path('review/<int:pk>/', ViewReview.as_view(), name="view-review"),
    path('ticket/delete/<int:pk>/', DeleteTicket.as_view(), name="delete-ticket"),
    path('review/delete/<int:pk>/', DeleteReview.as_view(), name="delete-review"),
    path('ticket/update/<int:pk>/', UpdateTicket.as_view(), name="update-ticket"),
    path('review/update/<int:pk>/', UpdateReview.as_view(), name="update-review"),
    #path('create/review/<int:pk>/', CreateReview.as_view(), name="create-review"),
]

src/flux/models.py
import os

from django.db import models
from django.conf import settings
from django.template.defaultfilters import slugify
from django.core.validators import MinValueValidator, MaxValueValidator
from PIL import Image

from LITReview.utils import rename_picture, resize_image


class Ticket(models.Model):
    title = models.CharField(max_length=128)
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    description = models.TextField(max_length=2048, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True, upload_to=rename_picture)
    time_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-time_created']
        verbose_name = "Ticket"

    def __str__(self):
        return f'TICKET {self.time_created.strftime("%Y - %H:%M:%S - %Z")} - {self.title}'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        elif not self.image:
            self.image = os.path.join('tickets', 'no-image-icon.png')
        super().save()
        resize_image(self.image.path, 'ticket_image').save(self.image.path)


class Review(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(default=0,
                                              validators=[MinValueValidator(0), MaxValueValidator(5)])
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    headline = models.CharField(max_length=128)
    body = models.TextField(max_length=8192, blank=True)
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'REVIEW {self.time_created.strftime("%Y - %H:%M:%S - %Z")} - {self.headline}'

    @property
    def get_rating(self):
        return round(self.rating)

src/flux/forms.py
from django.forms import ModelForm, RadioSelect, inlineformset_factory, Textarea, CharField

from .models import Ticket, Review


class CreateTicketForm(ModelForm):
    class Meta:
        model = Ticket
        labels = {
            'title': 'Titre:',
            'description': 'Description de votre demande de critique:',
            'image': 'Sélectionner une image de l\'article ou de la couverture du livre.'
        }
        fields = {'title', 'description', 'image'}
        widgets = {
            "description": Textarea(attrs={'cols': 100, 'rows': 25}),
        }


class CreateReviewForm(ModelForm):
    class Meta:
        CHOICES = [(str(x), str(x)) for x in range(0, 6)]
        model = Review
        labels = {
            'headline': 'Avis',
            'body': 'Votre critique:',
            'rating': 'Score'
        }
        fields = ['headline', 'body', 'rating']
        widgets = {'rating': RadioSelect(choices=CHOICES, attrs={'class': 'form-check-inline'})}


ReviewFormSet = inlineformset_factory(Ticket, Review, fields=('id', ))

src/flux/views.py
from itertools import chain

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Value, CharField, BooleanField
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from .models import Ticket, Review
from .forms import CreateTicketForm, CreateReviewForm
from followers.models import UserFollows


class Flux(LoginRequiredMixin, ListView):
    """
        Génere le flux de ticket/review pour l'utilisateur connecté.
    """
    model = Ticket
    template_name = "flux.html"
    context_object_name = "posts"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        ticket_with_review, ticket_without_review = get_users_viewable_tickets(get_users_viewable_ids(self.request))
        reviews = get_users_viewable_reviews(get_users_viewable_ids(self.request))
        feed = sorted(chain(*reviews, *ticket_with_review, *ticket_without_review), key=lambda post: post.time_created,
                      reverse=True)
        context['posts'] = feed
        return context


class MyPost(Flux):
    """
    Génere le flux de posts de l'utilisateur connecté.
    """

    def get_context_data(self, *, object_list=None, **kwargs):
        context = {}
        ticket_with_review, ticket_without_review = get_users_viewable_tickets([self.request.user.id])
        reviews = get_users_viewable_reviews([self.request.user.id])
        feed = sorted(chain(*reviews, *ticket_with_review, *ticket_without_review), key=lambda post: post.time_created,
                      reverse=True)
        context['mypost'] = True
        context['posts'] = feed
        print(context)
        return context


class CreateTicket(LoginRequiredMixin, CreateView):
    template_name = "create_ticket.html"
    model = Ticket
    form_class = CreateTicketForm
    success_url = reverse_lazy('blog:flux')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class CreateReview(LoginRequiredMixin, CreateView):
    template_name = "create_review.html"
    model = Review
    form_class = CreateTicketForm
    success_url = reverse_lazy('blog:flux')

    def get(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if kwargs and kwargs['pk'] != '0':
            ticket_form = CreateTicketForm(instance=Ticket.objects.get(pk=kwargs['pk']))
            ticket = Ticket.objects.get(pk=kwargs['pk'])
            review_form = CreateReviewForm()
            return self.render_to_response(self.get_context_data(ticket=ticket, review=review_form))
        else:
            ticket_form = CreateTicketForm()
            review_form = CreateReviewForm()
            return self.render_to_response(self.get_context_data(ticket=ticket_form, review=review_form))

    def post(self, request, *args, **kwargs):
        self.object = None
        if self.kwargs and kwargs['pk'] != '0':
            review_form = CreateReviewForm(self.request.POST, self.request.FILES)
            if review_form.is_valid():
                form = CreateTicketForm(instance=Ticket.objects.get(pk=kwargs['pk']))
                return self.form_valid(form, review_form)
            else:
                raise ValueError('Review Form invalid')

        else:
            form_class = self.get_form_class()
            form = self.get_form(form_class)
            review_form = CreateReviewForm(self.request.POST, self.request.FILES)
            if form.is_valid() and review_form.is_valid():
                return self.form_valid(form, review_form)

    def form_valid(self, form, review_form):
        if form:
            form.instance.user = self.request.user
            form.save()
            review_form.instance.ticket = Ticket.objects.get(pk=form.instance.pk)
            review_form.instance.user = self.request.user
            review_form.save()
            return super().form_valid(form)
        else:
            review_form.instance.ticket = Ticket.objects.get(pk=self.kwargs['pk'])
            review_form.instance.user = self.request.user
            review_form.save()
            return super().form_valid(review_form)


class UpdateTicket(LoginRequiredMixin, UpdateView):
    model = Ticket
    form_class = CreateTicketForm
    template_name = "update_ticket.html"
    context_object_name = "ticket"

    def get(self, request, *args, **kwargs):
        if self.request.user.id == Ticket.objects.get(pk=kwargs['pk']).user.id:
            return super().get(request, *args, **kwargs)
        else:
            return redirect('blog:flux')


class UpdateReview(LoginRequiredMixin, UpdateView):
    model = Review
    form_class = CreateReviewForm
    template_name = "update_review.html"
    context_object_name = "review"

    def get(self, request, *args, **kwargs):
        if self.request.user == Review.objects.get(pk=kwargs['pk']).user:
            return super().get(request, *args, **kwargs)
        else:
            return redirect('blog:flux')


class DeleteTicket(LoginRequiredMixin, DeleteView):
    model = Ticket
    template_name = 'delete_ticket.html'
    success_url = reverse_lazy('blog:flux')

    def get(self, request, *args, **kwargs):
        ticket = Ticket.objects.get(pk=kwargs['pk'])
        if kwargs['pk'] and request.user == ticket.user:
            self.object = self.get_object()
            context = self.get_context_data(object=self.object)
            return self.render_to_response(self.get_context_data(context=context, ticket=ticket))
        else:
            return redirect('blog:flux')


class DeleteReview(LoginRequiredMixin, DeleteView):
    model = Review
    template_name = 'delete_review.html'
    success_url = reverse_lazy('blog:flux')

    def get(self, request, *args, **kwargs):
        review = Review.objects.get(pk=kwargs['pk'])
        post = {}
        if kwargs['pk'] and request.user == review.user:
            self.object = self.get_object()
            context = self.get_context_data(object=self.object)
            post['ticket'] = Ticket.objects.get(pk=review.ticket_id)
            return self.render_to_response(self.get_context_data(context=context, post=post))
        else:
            return redirect('blog:flux')

    def get_object(self, queryset=None):
        obj = super().get_object()
        obj_ticket = Ticket.objects.get(pk=obj.ticket_id)

        return obj, obj_ticket

    def get_success_url(self):
        if self.success_url:
            return self.success_url

    def form_valid(self, form):
        success_url = self.get_success_url()
        [post_object.delete() for post_object in self.object]
        return HttpResponseRedirect(success_url)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        return redirect('blog:flux')


class ViewTicket(LoginRequiredMixin, DetailView):
    template_name = 'ticket.html'
    model = Ticket


class ViewReview(LoginRequiredMixin, DetailView):
    template_name = 'review.html'
    model = Review

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data()
        context['ticket'] = Ticket.objects.get(pk=context['review'].ticket.id)
        return context


def get_users_viewable_reviews(users_ids):
    """

    Args:
        users_ids: ids du ou des utilisateurs.

    Returns: Queryset de Review associées au ids.

    """

    return [
        Review.objects.filter(user_id=ids, ticket_id__isnull=False).annotate(content_type=Value('REVIEW', CharField()))
        for ids in users_ids]


def get_users_viewable_tickets(users_ids):
    """

    Args:
        users_ids: ids du ou des utilisateurs.

    Returns: Two list of QuerySet with TICKET annotation and Boolean has_review=True if ticket has review
            - ticket_with_review
            - ticket_without_review
    """

    ticket_with_review = [Ticket.objects.filter(user_id=ids, review__isnull=False).annotate(
        content_type=Value('TICKET', CharField()),
        has_review=Value(True, BooleanField())) for ids in users_ids]

    ticket_without_review = [
        Ticket.objects.filter(user_id=ids, review__isnull=True).annotate(
            content_type=Value('TICKET', CharField()),
            has_review=Value(False, BooleanField())) for ids in users_ids]
    return ticket_with_review, ticket_without_review


def get_users_viewable_ids(request):
    """

    Args:
        request: Données request id de l'utilisateur connecté.

    Returns: Liste d'ids utilisateur de l'on suit, qui nous suivent.

    """
    followed_users = [user.followed_user_id for user in UserFollows.objects.filter(user_id=request.user.id)]
    followed_users.append(request.user.id)
    return followed_users

src/flux/templates/base_flux.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}

    {% block flux %}
    {% endblock %}

{% endblock %}

src/flux/templates/create_review.html
{% extends 'base_flux.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

    {% if ticket.title|length > 1 %}

        <section id="post-content" class="container border border-2 rounded-3 my-2">
            <div id="post-header" class="row align-items-center py-3">
                <div id="post" class="row text-center"><h4>Vous réponsez à la critique:</h4></div>
            </div>
        </section>
        {% include 'ticket_snippet.html' with pk=ticket.id %}

    {% else %}
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
        <section id="post-content" class="container border border-2 rounded-3 my-2">
            <div id="post-header" class="row align-items-center py-3">
                <div class="col-12 text-center">Votre demande de crititique</div>
            </div>
            <div id="post" class="row text-start my-3">


                    <div class="col-6 text-start my-3">
                        {{ form.title.label_tag }} {{ form.title }}
                    </div>
                    <div class="col-12 my-3">
                        {{ form.description.label_tag }}
                        <br>
                        {{ form.description }}
                    </div>
                    <div class="col-12 my-3">
                        {{ form.image.label_tag }}
                        <br>
                        <div class="row">
                            <div class="col-4">
                                <h5>Image:</h5>
{#                                <img src="{% get_media_prefix %}{{ ticket.image }}" alt="">#}
                            </div>
                            <div class="col-6">
                                <h5>Changer d'image:</h5>
                                {{ form.image }}
                            </div>
                        </div>
                    </div>

                    {% for error in errors.values %}
                        <h3 style="color: red;">
                            {{ error }}
                        </h3>
                    {% endfor %}

            </div>
        </section>

    {% endif %}

    <section id="post-content" class="container border border-2 rounded-3 my-2">
        <div id="post-header" class="row align-items-center py-3">
            <div class="col-12 text-center">Votre crititique:</div>
        </div>
        <div id="post" class="row text-start my-3">


                <div class="col-6 text-start my-3">
                    {{ review.headline.label_tag }} {{ review.headline }}
                </div>
                <div class="col-12 my-3">
                    {{ review.body.label_tag }}
                    <br>
                    {{ review.body }}
                </div>
                <div class="col-12 my-3">
                    {{ review.rating.label_tag }}
                    <br>
                    {{ review.rating }}
                </div>
                <div class="row my-3">
                  <div class="col-12 text-center">
                        <input id="btn-ticket-submit" class="btn btn-primary my-3 text-center" type="submit" value="Demander la critique">
                  </div>
                </div>
                {% for error in errors.values %}
                    <h3 style="color: red;">
                        {{ error }}
                    </h3>
                {% endfor %}

        </div>
    </section>
</form>
    {% for error in errors.values %}
        <h3 style="color: red;">
            {{ error }}
        </h3>
    {% endfor %}

{% endblock %}

src/flux/templates/create_ticket.html
{% extends 'base_flux.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

    <section id="post-content" class="container border border-2 rounded-3 my-2">
        <div id="post-header" class="row align-items-center py-3">
            <div class="col-12 text-center">Votre demande de crititique</div>
        </div>
        <div id="post" class="row text-start my-3">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="col-6 text-start my-3">
                    {{ form.title.label_tag }} {{ form.title }}
                </div>
                <div class="col-12 my-3">
                    {{ form.description.label_tag }}
                    <br>
                    {{ form.description }}
                </div>
                <div class="col-12 my-3">
                    {{ form.image.label_tag }}
                    <br>
                    <div class="row">
                        <div class="col-4">
                            <h5>Image:</h5>
                            <img src="{% get_media_prefix %}{{ ticket.image }}" alt="">
                        </div>
                        <div class="col-6">
                            <h5>Changer d'image:</h5>
                            {{ form.image }}
                        </div>
                    </div>
                </div>

                {% for error in errors.values %}
                    <h3 style="color: red;">
                        {{ error }}
                    </h3>
                {% endfor %}

                <input id="btn-ticket-submit" class="btn btn-primary my-3" type="submit" value="Demander la critique">
            </form>
        </div>
    </section>

{% endblock %}

src/flux/templates/delete_review.html
{% extends 'base_flux.html' %}

{% block title %}{{ review.headline }}{% endblock %}

{% block content %}

      <section id="post-content" class="container border border-2 rounded-3 my-2">
            <div id="post-header" class="row align-items-center py-3">
                <div id="post" class="row text-center"><h4>Voulez vous supprimer :</h4></div>
            </div>
        </section>
        {% include 'review_snippet.html' %}

        <section id="post-content" class="container border border-2 rounded-3 my-2">
            <div id="post-header" class="row align-items-center py-3 text-center">
                <form method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" id="btn-ticket" class="btn btn-primary mb-3" value="Supprimer">
                </form>
            </div>
        </section>

{% endblock %}

src/flux/templates/delete_ticket.html
{% extends 'base_flux.html' %}

{% block title %}{{ ticket.title }}{% endblock %}

{% block content %}

      <section id="post-content" class="container border border-2 rounded-3 my-2">
            <div id="post-header" class="row align-items-center py-3">
                <div id="post" class="row text-center"><h4>Voulez vous supprimer :</h4></div>
            </div>
        </section>
        {% include 'ticket_snippet.html' with has_review=True %}
        <section id="post-content" class="container border border-2 rounded-3 my-2">
            <div id="post-header" class="row align-items-center py-3 text-center">
                <form method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" id="btn-ticket" class="btn btn-primary mb-3" value="Supprimer">
                </form>
            </div>
        </section>

{% endblock %}

src/flux/templates/flux.html
{% extends 'base_flux.html' %}
{% load static %}

{% block title %}LITReview - Articles{% endblock %}

{% block flux %}
    <div class="container my-2">
        <div class="d-grid d-md-block justify-content-center text-center">
            <a id="btn-flux" class="col-3 btn btn-primary" href="{% url 'blog:create-ticket' %}">Demander une critique</a>
            <a id="btn-flux" class="col-3 btn btn-primary" href="{% url 'blog:create-review' pk=00 %}">Créer une critique</a>
        </div>
    </div>
    {% for post in posts %}

        {% if post.content_type == 'TICKET' %}
            {% with has_review=post.has_review %}
                {% if not has_review %}
                    {% include 'ticket_snippet.html' with ticket=post mypost=mypost %}
                {% endif %}
            {% endwith %}
        {% elif post.content_type == 'REVIEW' %}
            {% include 'review_snippet.html' with review=post mypost=mypost %}
        {% endif %}
    {% endfor %}

{% endblock %}

src/flux/templates/review.html
{% extends 'base_flux.html' %}
{% load static %}

{% block title %}{{ ticket.title }}{% endblock %}

{% block content %}

    {% include 'review_snippet.html' with post=review %}

{% endblock %}

src/flux/templates/review_snippet.html
{% load static %}

{% block title %}{% endblock %}

{% block content %}

    <section id="post-content" class="container border border-2 rounded-3 my-2">
        <div id="post-header" class="row align-items-center py-3">
            <div class="col-4 text-start">
                {% if review.user_id == user.id %}
                    <h6><i>Vous</i> Avez publié une critique</h6>
                {% else %}
                    <h6><i>{{ review.user.nick_name }}</i> A publié une critique</h6>
                {% endif %}
            </div>
            <div class="col-8 text-end">
                <h6>Le: {{ review.time_created|date:"D d M Y" }} à {{ review.time_created|date:"H:i" }}</h6>
            </div>
        </div>

        <div class="row">
            <div class="col-10 text-start my-3">
                <h5>{{ review.headline }}</h5>
                <div class="review-feedback">
                    <span class="far fa-star {% if review.rating > 0 %} fas fa-star {% endif %}"></span>
                    <span class="far fa-star {% if review.rating > 1 %} fas fa-star {% endif %}"></span>
                    <span class="far fa-star {% if review.rating > 2 %} fas fa-star {% endif %}"></span>
                    <span class="far fa-star {% if review.rating > 3 %} fas fa-star {% endif %}"></span>
                    <span class="far fa-star {% if review.rating > 4 %} fas fa-star {% endif %}"></span>
                </div>
                <p>{{ review.body }}</p>
            </div>
        </div>

        {% with ticket=post.ticket has_review=True %}
            {% include 'ticket_snippet.html' %}
        {% endwith %}
        <div>
            {% if review.user_id == user.id and mypost %}
                <a id="btn-ticket" class="btn btn-primary mb-3" href="{% url 'blog:delete-review'  pk=review.id %}">Supprimer
                    la critique</a>
            {% endif %}
        </div>

    </section>



{% endblock %}

src/flux/templates/ticket.html
{% extends 'base_flux.html' %}
{% load static %}

{% block title %}{{ ticket.title }}{% endblock %}

{% block content %}

    {% include 'ticket_snippet.html' with post=ticket %}

{% endblock %}

src/flux/templates/ticket_snippet.html
{% load static %}

{%  block title %}{% endblock %}

{% block content %}

    <section id="post-content" class="container border border-2 rounded-3 my-2">
        <div id="post-header" class="row align-items-center py-3">
            <div class="col-4 text-start">
                {% if ticket.user_id == user.id %}
                    <h6><i>Vous</i> Avez demandé une critique</h6>
                {% else %}
                    <h6><i>{{ ticket.user.nick_name }}</i> A demandé une critique</h6>
                {% endif %}
            </div>
            <div class="col-8 text-end">
                <h6>Le: {{ ticket.time_created|date:"D d M Y" }} à {{ ticket.time_created|date:"H:i" }}</h6>
            </div>
        </div>
        <div class="row">
            <div class="col-10 text-start my-3">
                <h5>{{ ticket.title }}</h5>
            </div>
        </div>
        <div class="row">
            <div class="col-10">
                <img src="{% get_media_prefix %}{{ ticket.image }}" class="rounded float-start mx-3 mb-3" alt="">
                <p>{{ ticket.description }}</p>
            </div>
        </div>

        <div >

            {% if not has_review %}
                <a id="btn-ticket" class="btn btn-primary mb-3" href="{% url 'blog:create-review'  pk=ticket.id %}">Ajouter une critique</a>
                {% if ticket.user_id == user.id and mypost %}

                    <a id="btn-ticket" class="btn btn-primary mb-3" href="{% url 'blog:delete-ticket'  pk=ticket.id %}">Supprimer la demande de critique</a>
                {% endif %}
            {% endif %}

        </div>
    </section>

{% endblock %}

src/flux/templates/update_review.html
{% include 'create_review.html' with title=review.title%}

src/flux/templates/update_ticket.html
{% include 'create_ticket.html' with title=ticket.title%}